# 1) Mengonversi urutan Python ke NumPy Arrays 

Array NumPy dapat didefinisikan menggunakan urutan Python seperti daftar dan tupel. Daftar dan tupel didefinisikan menggunakan [...]dan (...), masing-masing. Daftar dan tupel dapat menentukan pembuatan ndarray:

-daftar angka akan membuat larik 1D,

-daftar daftar akan membuat larik 2D,

-daftar bersarang lebih lanjut akan membuat array berdimensi lebih tinggi. Secara umum, objek array apa pun disebut ndarray di NumPy.

## Import library

In [ ]:
import numpy as np

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

#### Array 1 dimensi

In [ ]:
print(a1D)

[1 2 3 4]


#### Array 2 dimensi

In [ ]:
print(a2D)

[[1 2]
 [3 4]]


#### Array 3 dimensi

In [ ]:
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# 2) Fungsi pembuatan array NumPy Intrinsik 

NumPy memiliki lebih dari 40 fungsi bawaan untuk membuat array seperti yang dijelaskan dalam rutinitas pembuatan Array . Fungsi-fungsi ini dapat dibagi menjadi kira-kira tiga kategori, berdasarkan dimensi array yang mereka buat:

1. array 1D

2. array 2D

3. ndarrays

###1 - Fungsi pembuatan larik 1D 
Fungsi pembuatan array 1D misalnya numpy.linspacedan numpy.arange umumnya membutuhkan setidaknya dua input, start dan stop.

numpy.arange membuat array dengan nilai yang bertambah secara teratur. Periksa dokumentasi untuk informasi lengkap dan contoh. Beberapa contoh ditunjukkan:

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Catatan: praktik terbaik untuk numpy.arange adalah menggunakan nilai awal, akhir, dan langkah bilangan bulat. Ada beberapa seluk-beluk tentang dtype. Dalam contoh kedua, dtype didefinisikan. Pada contoh ketiga, array adalah dtype=float untuk mengakomodasi ukuran langkah 0.1. Karena kesalahan pembulatan, stop nilai terkadang disertakan.

numpy.linspace akan membuat array dengan jumlah elemen tertentu, dan diberi jarak yang sama antara nilai awal dan akhir yang ditentukan. Sebagai contoh:

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

Keuntungan dari fungsi pembuatan ini adalah Anda menjamin jumlah elemen dan titik awal dan akhir. Yang sebelumnya tidak akan menyertakan nilai.arange (start, stop, step)stop

### 2 - Fungsi pembuatan array 2D 
Fungsi pembuatan array 2D misalnya numpy.eye, numpy.diag, dan numpy.vander mendefinisikan properti dari matriks khusus yang direpresentasikan sebagai array 2D.

np.eye(n, m) mendefinisikan matriks identitas 2D. Elemen di mana i=j (indeks baris dan indeks kolom sama) adalah 1 dan sisanya adalah 0, seperti:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

numpy.diag dapat mendefinisikan baik array 2D persegi dengan nilai yang diberikan sepanjang diagonal atau jika diberikan array 2D mengembalikan array 1D yang hanya elemen diagonal. Dua fungsi pembuatan array dapat membantu saat melakukan aljabar linier, seperti:

In [ ]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

vander(x, n) mendefinisikan matriks Vandermonde sebagai array NumPy 2D. Setiap kolom dari matriks Vandermonde adalah pangkat menurun dari larik atau daftar atau tupel 1D input, xdi mana orde polinomial tertinggi adalah n-1. Rutinitas pembuatan array ini sangat membantu dalam menghasilkan model kuadrat terkecil linier, seperti:

In [ ]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [ ]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [ ]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

###3 - fungsi pembuatan ndarray umum 

Fungsi pembuatan ndarray misalnya numpy.ones, numpy.zeros, dan random mendefinisikan array berdasarkan bentuk yang diinginkan. Fungsi pembuatan ndarray dapat membuat array dengan dimensi apa pun dengan menentukan berapa banyak dimensi dan panjang di sepanjang dimensi itu dalam sebuah tupel atau daftar.

numpy.zeros akan membuat array yang diisi dengan 0 nilai dengan bentuk yang ditentukan. Tipe-d default adalah float64:

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

numpy.ones akan membuat array yang diisi dengan 1 nilai. Ini identik dengan zerosdalam semua hal lain seperti:

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Metode random hasil default_rng akan membuat array yang diisi dengan nilai acak antara 0 dan 1. Ini disertakan dengan numpy.random perpustakaan. Di bawah ini, dua larik dibuat dengan masing-masing bentuk (2,3) dan (2,3,2). Benih diatur ke 42 sehingga Anda dapat mereproduksi angka pseudo random ini:

In [ ]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [ ]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

numpy.indices akan membuat satu set larik (ditumpuk sebagai larik berdimensi satu lebih tinggi), satu per dimensi dengan masing-masing mewakili variasi dalam dimensi itu:

In [ ]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

Hal ini sangat berguna untuk mengevaluasi fungsi beberapa dimensi pada grid biasa.



#3) Mereplikasi, menggabungkan, atau mengubah array yang ada 
Setelah Anda membuat array, Anda dapat mereplikasi, menggabungkan, atau mengubah array yang ada untuk membuat array baru. Saat Anda menetapkan array atau elemennya ke variabel baru, Anda harus secara eksplisit numpy.copyarray, jika tidak, variabel adalah tampilan ke dalam array asli. Perhatikan contoh berikut:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


Dalam contoh ini, Anda tidak membuat array baru. Anda membuat variabel b, yang melihat 2 elemen pertama dari a. Ketika Anda menambahkan 1 ke b, Anda akan mendapatkan hasil yang sama dengan menambahkan 1 ke a[:2]. Jika Anda ingin membuat array baru , gunakan numpy.copy rutin pembuatan array seperti:

In [ ]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


Ada beberapa rutin untuk bergabung dengan array yang ada misalnya numpy.vstack, numpy.hstack, dan numpy.block. Berikut adalah contoh menggabungkan empat larik 2-kali-2 ke dalam larik 4-kali-4 menggunakan block:

In [ ]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])